### PR TITLE
add --strip-attributes, which defaults to true

### PR DESCRIPTION
**Pull request by jakutis**

### CODE REVIEW

**Comment by shlomitc** [comment]
can you please explain a bit better what is the use case? why do you need it?
it looks like a very specific use case and a one that propagates deeply to all functions. maybe the icon you're working on was generated badly?

**Comment by itaibenda** [comment]
@shlomitc I think it would be a good idea to move the fill & stroke handling to one location so it won't be confusing.

The current existing scenarios:
1. monochrome on - removes fill & stroke altogether
2. monochrome off - sets fill & stroke to `currentColor` if it's not `none`

The scenario that @jakutis added: monochrome off & stripAttributes off - leaves the original fill & stroke

@jakutis from what I've seen so far when reseting to `currentColor` broke my SVG it was due to a bad SVG rather than the fact that I didn't want to strip the colors. Could you please share your SVG?

Also, it makes more sense to me to change the `monochrome` flag to be non-boolean (`remove`, `currentColor`, & `keep`) since we don't really have 2x2 options

**Comment by jakutis** [comment]
First things first, thank you @shlomitc for giving me an opportunity to write this essay.
And @itaibenda, for giving moral support, although the `--monochrome` feature is a different topic.

# Context

> can you please explain a bit better what is the use case?

It all started with [this original SVG](https://raw.githubusercontent.com/wix/svg2react-icon/example-icon-checkbox/examples/Checkboxbefore.svg).
Without the `--no-strip-attributes` feature that this pull request adds, it compiles to [this Icon](https://github.com/wix/svg2react-icon/blob/example-icon-checkbox/examples/Checkboxbefore-strip.tsx).
It is a colored disk with a white checkbox in it.
We place the icon on the top left corner of a rectangle with a colored border.

# Our issue

> maybe the icon you're working on was generated badly?

The compiled Icon works well on Google Chrome, so the icon is not generated badly.
But it does not work well on Microsoft Internet Explorer 11.
Unless [`<path>`](https://github.com/wix/svg2react-icon/blob/example-icon-checkbox/examples/Checkboxbefore-strip.tsx#L9) contains also a `fill="#FFF"` attribute, it renders the disk and does not render the checkbox.

# Why merge this pull request?

> why do you need it?

If this pull request is merged, then we can do just that - control the `fill` attribute and fix [Our Issue](#our-issue) by:
1. Adding a `--no-strip-attributes` CLI argument to `svg2react-icon` call.
2. Updating our original SVG to [this SVG](https://raw.githubusercontent.com/wix/svg2react-icon/example-icon-checkbox/examples/Checkboxbefore.svg) (`fill` is removed from `<circle>` and `fill="#FFF"` is set on `<polygon>`).
3. Verifying that the [new Icon](https://raw.githubusercontent.com/wix/svg2react-icon/example-icon-checkbox/examples/Checkboxafter-nostrip.tsx) has `<path>` with our precious `fill="#FFF"`!

# If you do not merge this pull request

Then we have only two other options to solve our issue.
Neither of them make sense, since the `color="#FFF"` is already written in the SVG and let through by `svg2react-icon` and used by Google Chrome.
But anyway, here, look at the ugly options:
1. Change SVG so that it cuts out checkbox from the circle and then place a small white `<div>` below the icon, so that the checkbox-shaped hole does not show the colored border of a rectangle that this icon is placed above, see section "Context".
2. Use SVG only to draw a checkbox and draw the circle using `<div>` with rounded corners.

**Comment by shlomitc** [comment]
We decided to solve such issues at the icon level.
icons should be created a single layer, so in that case, the change to the infrastructure is not required.

Thanks for the PR. Closing.

**Pull request closed without merging**
