### PR TITLE
fix: broken paths when creating icons in Win32

### PR DESCRIPTION
**Pull request by brakmic**
Added [slash](https://www.npmjs.com/package/slash) NPM package for *backslash-to-slash* conversions on Windows. Without this workaround the generation of **src/Icons/Index.js** with **wix-style-react** would produce paths like 

```typescript
export {default as Chat} from './components\Chat';
``` 

Such paths wouldn't be processed correctly on Windows. 

In fact the above backslash would be ignored and storyboard generation would stumble upon something like this: 

```typescript
export {default as Chat} from './componentsChat';
``` 

Therefore, I'd recommend to keep the slashes by using the [slash package](https://github.com/sindresorhus/slash)

I don't know if Windows platform is one of your target architectures but I could at least generate a working storyboard after having applied this patch. **Macs** are too expensive for me 😅 

Feel free to ignore this PR. 

Kind regards,

### CODE REVIEW

**Comment by brakmic** [comment]
Hi @itaibenda,

I'm getting there errors when running the latest tests (I think the CRLF-errors can be ignored, as this applies to Windows only):

  216:1    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  217:64   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  218:42   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  219:10   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  220:8    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  221:6    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  222:4    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 419 problems (419 errors, 0 warnings)

[11:46:05] Finished 'eslint' after 1829 ms
[11:46:06] Starting 'clean'...
[11:46:06] Finished 'clean' after 8 ms
[11:46:06] Starting 'sass'...
[11:46:06] Starting 'copyAssets'...
[11:46:07] Finished 'copyAssets' after 331 ms
[11:46:07] Finished 'sass' after 767 ms

> svg2react-icon@1.0.0 test d:\src\js\react\svg2react-icon
> yoshi test --jest

[11:46:07] Starting 'jest'...
 FAIL  test\build-icons.spec.js
  ● Build icons › should clean previous output dir and copy base files

    expect(received).toMatch(expected)

    Expected value to match:
      /.*\/dist\/components/
    Received:
      "\\dist\\components"

      at Object.it (test\build-icons.spec.js:118:48)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › should create a simple svg component

    expect(received).toEqual(expected)

    Expected value to equal:
      2
    Received:
      3

      at expectIconFiles (test\build-icons.spec.js:68:52)
      at buildIcons.then (test\build-icons.spec.js:134:7)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › should create a simple svg component

    expect(jest.fn()).not.toHaveBeenCalled()

    Expected mock function not to be called but it was called with:
      ["\\dist\\index.js", "export {default as Icon1} from \'./components/Icon1\';
    ", "utf-8"], ["/dist/components/Icon1.js"], ["\\dist\\index.js", "
    ", "utf-8"]

      at Object.afterEach (test\build-icons.spec.js:56:38)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › should create multiple svg components

    expect(string)[.not].toMatch(expected)

    string value must be a string.
    Received: undefined

      at svgFiles.forEach (test\build-icons.spec.js:73:57)
      at Array.forEach (native)
      at expectIconFiles (test\build-icons.spec.js:70:14)
      at buildIcons.then (test\build-icons.spec.js:152:7)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › should create multiple svg components

    expect(jest.fn()).not.toHaveBeenCalled()

    Expected mock function not to be called but it was called with:
      ["\\dist\\index.js", "export {default as Icon1} from \'./components/Icon1\';
    export {default as Icon2} from \'./components/Icon2\';
    ", "utf-8"], ["/dist/components/Icon2.js"], ["/dist/components/Icon1.js"]

      at Object.afterEach (test\build-icons.spec.js:56:38)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › svg modifications › should transform kebab-case attributes to camelCase

    expect(string)[.not].toMatch(expected)

    string value must be a string.
    Received: undefined

      at svgFiles.forEach (test\build-icons.spec.js:73:57)
      at Array.forEach (native)
      at expectIconFiles (test\build-icons.spec.js:70:14)
      at buildIcons.then (test\build-icons.spec.js:166:9)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › svg modifications › should transform kebab-case attributes to camelCase

    expect(jest.fn()).not.toHaveBeenCalled()

    Expected mock function not to be called but it was called with:
      ["\\dist\\index.js", "export {default as Icon2} from \'./components/Icon2\';
    ", "utf-8"], ["/dist/components/Icon2.js"]

      at Object.afterEach (test\build-icons.spec.js:56:38)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › svg modifications › should transform html attributes to React attributes

    expect(string)[.not].toMatch(expected)

    string value must be a string.
    Received: undefined

      at svgFiles.forEach (test\build-icons.spec.js:73:57)
      at Array.forEach (native)
      at expectIconFiles (test\build-icons.spec.js:70:14)
      at buildIcons.then (test\build-icons.spec.js:179:9)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › svg modifications › should transform html attributes to React attributes

    expect(jest.fn()).not.toHaveBeenCalled()

    Expected mock function not to be called but it was called with:
      ["\\dist\\index.js", "export {default as Icon3} from \'./components/Icon3\';
    ", "utf-8"], ["/dist/components/Icon3.js"]

      at Object.afterEach (test\build-icons.spec.js:56:38)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › svg modifications › should replace fill & stroke attributes with current color value

    expect(string)[.not].toMatch(expected)

    string value must be a string.
    Received: undefined

      at svgFiles.forEach (test\build-icons.spec.js:73:57)
      at Array.forEach (native)
      at expectIconFiles (test\build-icons.spec.js:70:14)
      at buildIcons.then (test\build-icons.spec.js:192:9)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › svg modifications › should replace fill & stroke attributes with current color value

    expect(jest.fn()).not.toHaveBeenCalled()

    Expected mock function not to be called but it was called with:
      ["\\dist\\index.js", "export {default as Icon4} from \'./components/Icon4\';
    ", "utf-8"], ["/dist/components/Icon4.js"]

      at Object.afterEach (test\build-icons.spec.js:56:38)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › svg modifications › should keep none value for stoke & fille attributes

    expect(string)[.not].toMatch(expected)

    string value must be a string.
    Received: undefined

      at svgFiles.forEach (test\build-icons.spec.js:73:57)
      at Array.forEach (native)
      at expectIconFiles (test\build-icons.spec.js:70:14)
      at buildIcons.then (test\build-icons.spec.js:205:9)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › svg modifications › should keep none value for stoke & fille attributes

    expect(jest.fn()).not.toHaveBeenCalled()

    Expected mock function not to be called but it was called with:
      ["\\dist\\index.js", "export {default as Icon5} from \'./components/Icon5\';
    ", "utf-8"], ["/dist/components/Icon5.js"]

      at Object.afterEach (test\build-icons.spec.js:56:38)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › svg modifications › should create typescript files if isTypeScriptOutput flag is set

    expect(string)[.not].toMatch(expected)

    string value must be a string.
    Received: undefined

      at svgFiles.forEach (test\build-icons.spec.js:97:57)
      at Array.forEach (native)
      at expectTypeScriptIconFiles (test\build-icons.spec.js:94:14)
      at buildIcons.then (test\build-icons.spec.js:218:9)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  ● Build icons › svg modifications › should create typescript files if isTypeScriptOutput flag is set

    expect(jest.fn()).not.toHaveBeenCalled()

    Expected mock function not to be called but it was called with:
      ["\\dist\\index.ts", "export {default as Icon5} from \'./components/Icon5\';
    ", "utf-8"], ["/dist/components/Icon5.tsx"]

      at Object.afterEach (test\build-icons.spec.js:56:38)
      at process._tickCallback (internal\process\next_tick.js:109:7)

  Build icons
    × should clean previous output dir and copy base files (5ms)
    × should create a simple svg component (11ms)
    × should create multiple svg components (3ms)
    svg modifications
      × should transform kebab-case attributes to camelCase (4ms)
      × should transform html attributes to React attributes (1ms)
      × should replace fill & stroke attributes with current color value (4ms)
      × should keep none value for stoke & fille attributes (2ms)
      × should create typescript files if isTypeScriptOutput flag is set (1ms)

Test Suites: 1 failed, 1 total
Tests:       8 failed, 8 total
Snapshots:   0 total
Time:        1.882s
Ran all test suites.
[11:46:09] Failed 'jest' after 2189 ms
jest failed
npm ERR! Test failed.  See above for more details.

**Comment by 3LOK** [comment]
@malsomnus encountered the same issue. what's the eta for this pull request?

**Comment by itaibenda** [comment]
@3LOK @malsomnus I've pushed an alternative fix: https://github.com/wix/svg2react-icon/commit/6267f71fdf18996e4883997d0a8e3f16cd790dd2
Please let me know if this helps

**Comment by itaibenda** [comment]
resolved in https://github.com/wix/svg2react-icon/commit/6267f71fdf18996e4883997d0a8e3f16cd790dd2

**Pull request closed without merging**
